# test bigquery

In [3]:
import os
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery

In [4]:
import google.auth
credentials, project = google.auth.default()
print("Compte utilisé par Python :", credentials.service_account_email if hasattr(credentials, 'service_account_email') else "Compte utilisateur (gcloud)")
print("Projet détecté par défaut :", project)

Compte utilisé par Python : hydrosense-bigquery@hydro-sense-498112.iam.gserviceaccount.com
Projet détecté par défaut : hydro-sense-498112

In [5]:
# 1 Connexion

# 1.1 Charge les variables du fichier .env
load_dotenv(dotenv_path="../.env")

# 1.2. Récupère la valeur de la variable d'environnement
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")

# 1.3. Initialise le client avec la variable définie
client = bigquery.Client(project=GCP_PROJECT_ID)

print(f"Connecté à {GCP_PROJECT_ID} ✅")

Connecté à hydro-sense-498112 ✅

In [6]:
# 2 Load test model "piezo_test"

print(os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))
print(os.getenv("GCP_PROJECT_ID"))

DATASET = os.getenv("BQ_DATASET_ID")
TABLE = "piezo_test"

query = f"""
    SELECT *
    FROM {GCP_PROJECT_ID}.{DATASET}.{TABLE}
    LIMIT 100
"""

query_job = client.query(query)
result = query_job.result()
df = result.to_dataframe()
df.head()

/Users/romainhuchet/code/charourou//Projet_Hydrosense/secrets/hydro-sense-498112-d8b48c4804b5.json
hydro-sense-498112

/Users/romainhuchet/.pyenv/versions/3.10.6/envs/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

                                  string_field_0
0  date_mesure;niveau_nappe_eau;profondeur_nappe
1                          1990-09-03;31.85;8.25
2                          1990-11-13;30.95;9.15
3                          1991-02-21;33.54;6.56
4                          1991-05-13;33.55;6.55

In [7]:
# problem of parsing ?? régler plus tard ??

In [8]:
# 3 test uploadinf

#df_test = pd.read_csv(f'../raw_data/piezo_BSS001BLTP.csv', sep = ';')
df_test = pd.read_csv(f'./data/piezo_bourdet_clean.csv', sep = ',')
df_test.head()

  date_mesure  niveau_nappe_eau
0  1994-02-01             13.45
1  1994-02-02             13.55
2  1994-02-03             13.79
3  1994-02-04             13.80
4  1994-02-05             13.79

In [9]:
TABLE = "piezo_bourdet_test"

table = f"{GCP_PROJECT_ID}.{DATASET}.{TABLE}"

client = bigquery.Client()

write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
job_config = bigquery.LoadJobConfig(write_disposition=write_mode)

job = client.load_table_from_dataframe(df_test, table, job_config=job_config)
result = job.result()

/Users/romainhuchet/.pyenv/versions/3.10.6/envs/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

In [11]:
TABLE = "piezo_bourdet_test"

query = f"""
    SELECT *
    FROM {GCP_PROJECT_ID}.{DATASET}.{TABLE}
    LIMIT 100
"""

query_job = client.query(query)
result = query_job.result()
df = result.to_dataframe()
df.head()

/Users/romainhuchet/.pyenv/versions/3.10.6/envs/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  date_mesure  niveau_nappe_eau
0  1995-08-28              7.37
1  1995-08-29              7.38
2  1995-08-30              7.38
3  1995-08-27              7.39
4  1995-08-31              7.39

In [12]:
df_test = pd.read_csv(f'./data/piezo_saint_fraigne_clean.csv', sep = ',')
df_test.head()

  date_mesure  niveau_nappe_eau
0  2002-08-01             76.58
1  2002-08-02             76.59
2  2002-08-03             76.59
3  2002-08-04             76.59
4  2002-08-05             76.59

In [13]:
TABLE = "piezo_saint_fraigne_test"

table = f"{GCP_PROJECT_ID}.{DATASET}.{TABLE}"

client = bigquery.Client()

write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
job_config = bigquery.LoadJobConfig(write_disposition=write_mode)

job = client.load_table_from_dataframe(df_test, table, job_config=job_config)
result = job.result()

/Users/romainhuchet/.pyenv/versions/3.10.6/envs/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(